name: QA Table Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape-sum:
    name: scrape-and-sum by 23f1000129@ds.study.iitm.ac.in
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npx playwright install

      - name: Run Playwright script
        run: node sum-tables.js
